
-- Books table
CREATE TABLE books (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR2(100),
  author VARCHAR2(100),
  available CHAR(1),
  CONSTRAINT pk_books PRIMARY KEY (id)
);

-- Log table
CREATE TABLE book_log (
  log_id NUMBER GENERATED ALWAYS AS IDENTITY,
  book_title VARCHAR2(100),
  action_date DATE DEFAULT SYSDATE,
  CONSTRAINT pk_book_log PRIMARY KEY (log_id)
);

-- Procedure: add_book
CREATE OR REPLACE PROCEDURE add_book (
  p_title     IN VARCHAR2,
  p_author    IN VARCHAR2,
  p_available IN CHAR
) AS
BEGIN
  INSERT INTO books (title, author, available) VALUES (p_title, p_author, p_available);
END;
/
SHOW ERRORS

-- Function: get_book_count
CREATE OR REPLACE FUNCTION get_book_count RETURN NUMBER AS
  total NUMBER;
BEGIN
  SELECT COUNT(*) INTO total FROM books;
  RETURN total;
END;
/
SHOW ERRORS

-- Trigger: log on insert
CREATE OR REPLACE TRIGGER trg_log_book_insert
AFTER INSERT ON books
FOR EACH ROW
BEGIN
  INSERT INTO book_log (book_title) VALUES (:NEW.title);
END;
/
SHOW ERRORS
